name:                pact-web-server
version:             0.0.0.0
github:              "CSVdB/sample-code"
license:             AllRightsReserved
author:              "Nick Van den Broeck"
maintainer:          "vandenbroeck@cs-vdb.com"
copyright:           "Copyright (c) 2021 Nick Van den Broeck"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - data-default
  - envparse
  - file-embed
  - http-client
  - http-client-tls
  - lens
  - monad-logger
  - optparse-applicative
  - pact-db
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - pretty-show
  - shakespeare
  - template-haskell
  - text
  - wai-extra
  - warp
  - yaml
  - yamlparse-applicative
  - yesod
  - yesod-auth
  - yesod-static

executables:
  pact-web-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pact-web-server

tests:
  pact-web-server-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity
    - genvalidity-hspec
    - genvalidity-text
    - hspec
    - http-client
    - monad-logger
    - lens
    - pact-db
    - pact-web-server
    - password
    - path-io
    - persistent
    - persistent-sqlite
    - QuickCheck
    - sydtest
    - sydtest-wai
    - sydtest-yesod
    - text
    - yesod
    - yesod-auth
